[pytest]
testpaths =
    test/int
    test/pgproto
    test/harness
    test/tools
addopts =
    -rsfE -v --showlocals --dist=loadgroup
markers =
    webui
    required_rolling_versions
    skip_asan: mark test to be skipped when running with --skip-asan (sanitizer builds)
timeout = 120
log_format = %(asctime)s.%(msecs)03d %(levelname)s [%(filename)s:%(lineno)d] %(message)s
log_date_format = %Y-%m-%d %H:%M:%S
