{
 "title": "Picodata",
 "description": "picodata dashboard",
 "tags": [ "picodata" ],
 "time": { "from": "now-3h", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   { "name": "prometheus", "label": "Datasource", "query": "prometheus" },
   {
    "name": "job",
    "label": "job",
    "query": {
     "query": "label_values(tnt_info_uptime,job)"
    }
   },
   {
    "name": "instance",
    "label": "Instances",
    "query": {
     "query": "label_values(up{job=~\"$job\"},instance)"
    }
   }
  ]
 },
 "panels": [
  { "title": "Picodata Cluster overview", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Cluster status overview",
   "type": "table",
   "description": "Overview of Picodata instances observed by Prometheus job.\n\nIf instance row is *red*, it means Prometheus can't reach\nURI specified in targets or ran into error.\nIf instance row is *green*, it means instance is up and running and\nPrometheus is successfully extracting metrics from it.\n\"Uptime\" column shows time since instant start.\n\nInstance instance filtering is disabled here.\n\nIf Prometheus job filter is not specified, displays running instances\nand ignores unreachable instances (we have no specific source to fetch)\n",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
   "targets": [
    {
     "expr": "up{job=~\"$job\"} * on(instance) group_left(alias) tnt_info_uptime{job=~\"$job\"} or\r\non(instance) label_replace(up{job=~\"$job\"}, \"alias\", \"Down\", \"instance\", \".*\")"
    }
   ]
  },
  {
   "type": "stat",
   "description": "Count of running Picodata instances observed by Prometheus job.\nIf Prometheus can't reach URI specified in targets\nor ran into error, instance is not counted.\n\nInstance instance filtering is disabled here.\n",
   "gridPos": { "h": 4, "w": 6, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum(up{job=~\"$job\"})"
    }
   ]
  },
  {
   "type": "stat",
   "description": "Overall value of memory available for Tarantool items",
   "gridPos": { "h": 4, "w": 3, "x": 18, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum(tnt_slab_quota_size{job=~\"$job\"})"
    }
   ]
  },
  {
   "type": "stat",
   "description": "Overall value of memory used by Picodata\nitems and indexes (*arena_used* value).\nIf Picodata instance is not available\nfor Prometheus metrics extraction now,\nits contribution is not counted.\n\nInstance instance filtering is disabled here.\n",
   "gridPos": { "h": 4, "w": 3, "x": 21, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum(tnt_slab_arena_used{job=~\"$job\"})"
    }
   ]
  },
  {
   "type": "stat",
   "description": "Count of running Picodata instances observed by Prometheus job.\nIf Prometheus can't reach URI specified in targets\nor ran into error, instance is not counted.\n\nInstance instance filtering is disabled here.\n",
   "gridPos": { "h": 4, "w": 6, "x": 12, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "count(up{job=~\"$job\"}) - sum(up{job=~\"$job\"})"
    }
   ]
  },
  {
   "type": "stat",
   "description": "Overall rate of network requests processed on Picodata instances.\nIf Picodata instance is not available for Prometheus metrics\nextraction now, its contribution is not counted.\n\nInstance instance filtering is disabled here.\n",
   "gridPos": { "h": 4, "w": 3, "x": 18, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum(rate(tnt_net_requests_total{job=~\"$job\"}[$__rate_interval]))"
    }
   ]
  },
  {
   "type": "stat",
   "description": "Overall rate of operations performed on Picodata spaces\n(*select*, *insert*, *update* etc.).\nIf Picodata instance is not available for Prometheus metrics\nextraction now, its contribution is not counted.\n\nInstance instance filtering is disabled here.\n",
   "gridPos": { "h": 4, "w": 3, "x": 21, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum(rate(tnt_stats_op_total{job=~\"$job\"}[$__rate_interval]))"
    }
   ]
  },
  {
   "title": "memtx used ratio",
   "type": "timeseries",
   "description": "memtx used ratio",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "tnt_slab_arena_used{instance=~\"$instance\",job=~\"$job\"} / tnt_slab_quota_size {instance=~\"$instance\",job=~\"$job\"} * 100",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "CPU overall by all instances",
   "type": "timeseries",
   "description": "This is the average share of time\nspent by all instance process executing in user and system mode.\nMetrics obtained using `getrusage()` call.\n",
   "gridPos": { "h": 8, "w": 7, "x": 8, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "sum (irate(tnt_cpu_user_time{instance=~\"$instance\", job=~\"$job\"}[$__rate_interval]) + irate(tnt_cpu_system_time{instance=~\"$instance\", job=~\"$job\"}[$__rate_interval])) / count(up{instance=~\"$instance\", job=~\"$job\"})",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Picodata instance status",
   "type": "timeseries",
   "description": "`master` status means instance is available for read and\nwrite operations. `replica` status means instance is\navailable only for read operations.\n\nPanel works with `metrics >= 0.11.0` and Grafana 8.x.\n",
   "gridPos": { "h": 8, "w": 9, "x": 15, "y": 9 },
   "targets": [
    {
     "expr": "tnt_read_only{instance=~\"$instance\",job=~\"$job\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  { "title": "Picodata Replication overview", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 17 } },
  {
   "title": "Picodata replication status",
   "type": "timeseries",
   "description": "`follows` status means replication is running.\nOtherwise, `not running` is displayed.\n\nPanel works with `metrics >= 0.13.0` and Grafana 8.x.\n",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 18 },
   "targets": [
    {
     "expr": "tnt_replication_status{instance=~\"$instance\",job=~\"$job\"}",
     "legendFormat": "{{instance}} {{stream}} ({{id}})"
    }
   ]
  },
  {
   "title": "Picodata replication lag",
   "type": "timeseries",
   "description": "Replication lag value for Picodata instance.\n\nPanel works with `metrics >= 0.13.0`.\n",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "tnt_replication_lag{instance=~\"$instance\",job=~\"$job\"}",
     "legendFormat": "{{instance}} ({{id}})"
    }
   ]
  },
  {
   "title": "Instances clock delta",
   "type": "timeseries",
   "description": "Clock drift across the cluster.\nmax shows difference with the fastest clock (always positive),\nmin shows difference with the slowest clock (always negative).\n\nPanel works with `metrics >= 0.10.0`.\n",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "tnt_clock_delta{instance=~\"$instance\",job=~\"$job\"}",
     "legendFormat": "{{instance}} ({{delta}})"
    }
   ]
  },
  {
   "title": "Synchronous queue owner",
   "type": "timeseries",
   "description": "Instance ID of the current synchronous replication master.\n\nPanel works with metrics 0.15.0 or newer, Picodata 2.8.1 or newer.\n",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "tnt_synchro_queue_owner{instance=~\"$instance\",job=~\"$job\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Synchronous queue owner",
   "type": "timeseries",
   "description": "Instance ID of the current synchronous replication master.\n\nPanel works with metrics 0.15.0 or newer, Picodata 2.8.1 or newer.\n",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "tnt_synchro_queue_owner{instance=~\"$instance\",job=~\"$job\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Synchronous queue transactions",
   "type": "timeseries",
   "description": "Count of transactions collecting confirmations now.\n\nPanel works with metrics 0.15.0 or newer, Picodata 2.8.1 or newer.\n",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "tnt_synchro_queue_len{instance=~\"$instance\",job=~\"$job\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Synchronous queue busy",
   "type": "timeseries",
   "description": "Whether the queue is processing any system entry (CONFIRM/ROLLBACK/PROMOTE/DEMOTE).\n\nPanel works with Grafana 8.x.\n\nPanel works with metrics 0.15.0 or newer, Picodata 2.8.1 or newer.\n",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 26 },
   "targets": [
    {
     "expr": "tnt_synchro_queue_busy{instance=~\"$instance\",job=~\"$job\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Picodata network activity",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 34 },
   "collapsed": true,
   "panels": [
    {
     "title": "Net memory",
     "type": "timeseries",
     "description": "Memory used for network input/output buffers.\n",
     "gridPos": { "h": 8, "w": 8, "x": 0, "y": 35 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "tnt_info_memory_net{instance=~\"$instance\",job=~\"$job\"}",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "Data received",
     "type": "timeseries",
     "description": "Data received by instance from binary protocol connections.\nGraph shows average bytes per second.\n",
     "gridPos": { "h": 8, "w": 8, "x": 8, "y": 35 },
     "fieldConfig": { "defaults": { "unit": "Bps" } },
     "targets": [
      {
       "expr": "rate(tnt_net_received_total{instance=~\"$instance\",job=~\"$job\"}[$__rate_interval])",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "Data sent",
     "type": "timeseries",
     "description": "Data sent by instance with binary protocol connections.\nGraph shows average bytes per second.\n",
     "gridPos": { "h": 8, "w": 8, "x": 16, "y": 35 },
     "fieldConfig": { "defaults": { "unit": "Bps" } },
     "targets": [
      {
       "expr": "rate(tnt_net_sent_total{instance=~\"$instance\",job=~\"$job\"}[$__rate_interval])",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "Network requests handled",
     "type": "timeseries",
     "description": "Number of network requests this instance has handled.\nGraph shows mean rps.\n",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 43 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "rate(tnt_net_requests_total{instance=~\"$instance\",job=~\"$job\"}[$__rate_interval])",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "Network requests pending",
     "type": "timeseries",
     "description": "Number of pending network requests.\n",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 43 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "tnt_net_requests_current{instance=~\"$instance\",job=~\"$job\"}",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "Processed requests",
     "type": "timeseries",
     "description": "Average number of requests processed by tx thread per second.\n\nPanel works with `metrics >= 0.13.0` and `Picodata >= 2.10-beta2`.\n",
     "gridPos": { "h": 8, "w": 6, "x": 0, "y": 51 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "rate(tnt_net_requests_in_progress_total{instance=~\"$instance\",job=~\"$job\"}[$__rate_interval])",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "Requests in progress",
     "type": "timeseries",
     "description": "Number of requests currently being processed in the tx thread.\n\nPanel works with `metrics >= 0.13.0` and `Picodata >= 2.10-beta2`.\n",
     "gridPos": { "h": 8, "w": 6, "x": 6, "y": 51 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "tnt_net_requests_in_progress_current{instance=~\"$instance\",job=~\"$job\"}",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "Requests in queue (overall)",
     "type": "timeseries",
     "description": "Average number of requests which was placed in queues\nof streams per second.\n\nPanel works with `metrics >= 0.13.0` and `Picodata >= 2.10-beta2`.\n",
     "gridPos": { "h": 8, "w": 6, "x": 12, "y": 51 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "rate(tnt_net_requests_in_stream_queue_total{instance=~\"$instance\",job=~\"$job\"}[$__rate_interval])",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "Requests in queue (current)",
     "type": "timeseries",
     "description": "Number of requests currently waiting in queues of streams.\n\nPanel works with `metrics >= 0.13.0` and `Picodata >= 2.10-beta2`.\n",
     "gridPos": { "h": 8, "w": 6, "x": 18, "y": 51 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "tnt_net_requests_in_stream_queue_current{instance=~\"$instance\",job=~\"$job\"}",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "New binary connections",
     "type": "timeseries",
     "description": "Average number of new binary protocol connections per second.\n",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 59 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "rate(tnt_net_connections_total{instance=~\"$instance\",job=~\"$job\"}[$__rate_interval])",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "Current binary connections",
     "type": "timeseries",
     "description": "Number of current active binary protocol connections.\n",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 59 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "tnt_net_connections_current{instance=~\"$instance\",job=~\"$job\"}",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "Data sent (per thread)",
     "type": "timeseries",
     "description": "Data sent by instance with binary protocol connections,\nseparated per thread.\nGraph shows average bytes per second.\n\nPanel works with metrics 0.15.0 or newer, Picodata 2.10 or newer.\n",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 67 },
     "fieldConfig": { "defaults": { "unit": "Bps" } },
     "targets": [
      {
       "expr": "rate(tnt_net_per_thread_sent_total{instance=~\"$instance\",job=~\"$job\"}[$__rate_interval])",
       "legendFormat": "{{instance}} (thread {{thread}})"
      }
     ]
    },
    {
     "title": "Data received (per thread)",
     "type": "timeseries",
     "description": "Data received by instance from binary protocol connections,\nseparated per thread.\nGraph shows average bytes per second.\n\nPanel works with metrics 0.15.0 or newer, Picodata 2.10 or newer.\n",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 67 },
     "fieldConfig": { "defaults": { "unit": "Bps" } },
     "targets": [
      {
       "expr": "rate(tnt_net_per_thread_received_total{instance=~\"$instance\",job=~\"$job\"}[$__rate_interval])",
       "legendFormat": "{{instance}} (thread {{thread}})"
      }
     ]
    },
    {
     "title": "New binary connections (per thread)",
     "type": "timeseries",
     "description": "Average number of new binary protocol connections per second,\nseparated per thread.\n\nPanel works with metrics 0.15.0 or newer, Picodata 2.10 or newer.\n",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 75 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "rate(tnt_net_per_thread_connections_total{instance=~\"$instance\",job=~\"$job\"}[$__rate_interval])",
       "legendFormat": "{{instance}} (thread {{thread}})"
      }
     ]
    },
    {
     "title": "Current binary connections (per thread)",
     "type": "timeseries",
     "description": "Number of current active binary protocol connections,\nseparated per thread.\n\nPanel works with metrics 0.15.0 or newer, Picodata 2.10 or newer.\n",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 75 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "tnt_net_per_thread_connections_current{instance=~\"$instance\",job=~\"$job\"}",
       "legendFormat": "{{instance}} (thread {{thread}})"
      }
     ]
    },
    {
     "title": "Network requests handled (per thread)",
     "type": "timeseries",
     "description": "Number of network requests this instance has handled,\nseparated per thread.\nGraph shows mean rps.\n\nPanel works with metrics 0.15.0 or newer, Picodata 2.10 or newer.\n",
     "gridPos": { "h": 8, "w": 8, "x": 0, "y": 83 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "rate(tnt_net_per_thread_requests_total{instance=~\"$instance\",job=~\"$job\"}[$__rate_interval])",
       "legendFormat": "{{instance}} (thread {{thread}})"
      }
     ]
    },
    {
     "title": "Processed requests (per thread)",
     "type": "timeseries",
     "description": "Average number of requests processed per second,\nseparated per thread.\n\nPanel works with metrics 0.15.0 or newer, Picodata 2.10 or newer.\n",
     "gridPos": { "h": 8, "w": 8, "x": 8, "y": 83 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "rate(tnt_net_per_thread_requests_in_progress_total{instance=~\"$instance\",job=~\"$job\"}[$__rate_interval])",
       "legendFormat": "{{instance}} (thread {{thread}})"
      }
     ]
    },
    {
     "title": "Requests in queue (overall per thread)",
     "type": "timeseries",
     "description": "Average number of requests which was placed in queues\nof streams per second, separated per thread.\n\nPanel works with metrics 0.15.0 or newer, Picodata 2.10 or newer.\n",
     "gridPos": { "h": 8, "w": 8, "x": 16, "y": 83 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "rate(tnt_net_per_thread_requests_in_stream_queue_total{instance=~\"$instance\",job=~\"$job\"}[$__rate_interval])",
       "legendFormat": "{{instance}} (thread {{thread}})"
      }
     ]
    },
    {
     "title": "Network requests pending (per thread)",
     "type": "timeseries",
     "description": "Number of pending network requests,\nseparated per thread.\n\nPanel works with metrics 0.15.0 or newer, Picodata 2.10 or newer.\n",
     "gridPos": { "h": 8, "w": 8, "x": 0, "y": 91 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "tnt_net_per_thread_requests_current{instance=~\"$instance\",job=~\"$job\"}",
       "legendFormat": "{{instance}} (thread {{thread}})"
      }
     ]
    },
    {
     "title": "Requests in progress (per thread)",
     "type": "timeseries",
     "description": "Number of requests currently being processed,\nseparated per thread.\n\nPanel works with metrics 0.15.0 or newer, Picodata 2.10 or newer.\n",
     "gridPos": { "h": 8, "w": 8, "x": 8, "y": 91 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "tnt_net_per_thread_requests_in_progress_current{instance=~\"$instance\",job=~\"$job\"}",
       "legendFormat": "{{instance}} (thread {{thread}})"
      }
     ]
    },
    {
     "title": "Requests in queue (current per thread)",
     "type": "timeseries",
     "description": "Number of requests currently waiting in queues of streams,\nseparated per thread.\n\nPanel works with metrics 0.15.0 or newer, Picodata 2.10 or newer.\n",
     "gridPos": { "h": 8, "w": 8, "x": 16, "y": 91 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "tnt_net_per_thread_requests_in_stream_queue_current{instance=~\"$instance\",job=~\"$job\"}",
       "legendFormat": "{{instance}} (thread {{thread}})"
      }
     ]
    }
   ]
  },
  {
   "title": "Picodata memtx allocation overview",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 35 }
  },
  {
   "title": "Slab allocator monitoring information",
   "type": "text",
   "gridPos": { "h": 3, "w": 24, "x": 0, "y": 36 },
   "options": {
    "content": "`quota_used_ratio` > 90%, `arena_used_ratio` > 90%, 50% < `items_used_ratio` < 90% – your memory is highly fragmented. See [docs](https://www.Picodata.io/en/doc/1.10/reference/reference_lua/box_slab/#lua-function.box.slab.info) for more info.\n\n`quota_used_ratio` > 90%, `arena_used_ratio` > 90%, `items_used_ratio` > 90% – you are running out of memory. You should consider increasing Picodata’s memory limit (*box.cfg.memtx_memory*).\n"
   }
  },
  {
   "title": "Used by slab allocator (quota_used_ratio)",
   "type": "timeseries",
   "description": "`quota_used_ratio` = `quota_used` / `quota_size`.\n\n`quota_used` – used by slab allocator (for both tuple and index slabs).\n\n`quota_size` – memory limit for slab allocator (as configured in the *memtx_memory* parameter).\n",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 39 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "tnt_slab_quota_used_ratio{instance=~\"$instance\",job=~\"$job\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Used for tuples and indexes (arena_used_ratio)",
   "type": "timeseries",
   "description": "`arena_used_ratio` = `arena_used` / `arena_size`.\n\n`arena_used` – used for both tuples and indexes.\n\n`arena_size` – allocated for both tuples and indexes.\n",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 39 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "tnt_slab_arena_used_ratio{instance=~\"$instance\",job=~\"$job\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Used for tuples (items_used_ratio)",
   "type": "timeseries",
   "description": "`items_used_ratio` = `items_used` / `items_size`.\n\n`items_used` – used only for tuples.\n\n`items_size` – allocated only for tuples.\n",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 39 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "tnt_slab_items_used_ratio{instance=~\"$instance\",job=~\"$job\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Used by slab allocator (quota_used)",
   "type": "timeseries",
   "description": "Memory used by slab allocator (for both tuple and index slabs).\n",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 47 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "tnt_slab_quota_used{instance=~\"$instance\",job=~\"$job\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Used for tuples and indexes (arena_used)",
   "type": "timeseries",
   "description": "Memory used for both tuples and indexes.\n",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 47 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "tnt_slab_arena_used{instance=~\"$instance\",job=~\"$job\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Used for tuples (items_used)",
   "type": "timeseries",
   "description": "Memory used for only tuples.\n",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 47 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "tnt_slab_items_used{instance=~\"$instance\",job=~\"$job\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Slab allocator memory limit (quota_size)",
   "type": "timeseries",
   "description": "Memory limit for slab allocator (as configured in the *memtx_memory* parameter).\n",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 55 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "tnt_slab_quota_size{instance=~\"$instance\",job=~\"$job\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Allocated for tuples and indexes (arena_size)",
   "type": "timeseries",
   "description": "Memory allocated for both tuples and indexes by slab allocator.\n",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 55 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "tnt_slab_arena_size{instance=~\"$instance\",job=~\"$job\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Allocated for tuples (items_size)",
   "type": "timeseries",
   "description": "Memory allocated for only tuples by slab allocator.\n",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 55 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "tnt_slab_items_size{instance=~\"$instance\",job=~\"$job\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Picodata MVCC overview",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 63 },
   "collapsed": true,
   "panels": [
    {
     "title": "Transaction statements size (total)",
     "type": "timeseries",
     "description": "Each operation like `space:replace{}` turns into ``statement``\nfor the current transaction.\n\nGraph shows the number of bytes that are allocated\nfor the statements of all current transactions.\n\nPanel works with metrics 0.15.1 or newer, Picodata 2.10 or newer.\n",
     "gridPos": { "h": 8, "w": 8, "x": 0, "y": 5 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "tnt_memtx_tnx_statements{instance=~\"$instance\",job=~\"$job\",kind=\"total\"}",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "Transaction statements size (average)",
     "type": "timeseries",
     "description": "Each operation like `space:replace{}` turns into ``statement``\nfor the current transaction.\n\nGraph shows average bytes used by transactions for statements\n(`txn.statements.total` bytes / number of open transactions).\n\nPanel works with metrics 0.15.1 or newer, Picodata 2.10 or newer.\n",
     "gridPos": { "h": 8, "w": 8, "x": 8, "y": 5 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "tnt_memtx_tnx_statements{instance=~\"$instance\",job=~\"$job\",kind=\"average\"}",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "Transaction statements size (max)",
     "type": "timeseries",
     "description": "Each operation like `space:replace{}` turns into ``statement``\nfor the current transaction.\n\nGraph shows the maximum number of bytes used by one\nthe current transaction for statements.\n\nPanel works with metrics 0.15.1 or newer, Picodata 2.10 or newer.\n",
     "gridPos": { "h": 8, "w": 8, "x": 16, "y": 5 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "tnt_memtx_tnx_statements{instance=~\"$instance\",job=~\"$job\",kind=\"max\"}",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "Transaction user size (total)",
     "type": "timeseries",
     "description": "User may allocate memory for the current transaction with\nPicodata C APIfunction `box_txn_alloc()`.\n\nGraph shows memory allocated for all current transactions.\n\nPanel works with metrics 0.15.1 or newer, Picodata 2.10 or newer.\n",
     "gridPos": { "h": 8, "w": 8, "x": 0, "y": 13 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "tnt_memtx_tnx_user{instance=~\"$instance\",job=~\"$job\",kind=\"total\"}",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "Transaction user size (average)",
     "type": "timeseries",
     "description": "User may allocate memory for the current transaction with\nPicodata C APIfunction `box_txn_alloc()`.\n\nGraph shows transaction average\n(total allocated bytes / number of all current transactions).\n\nPanel works with metrics 0.15.1 or newer, Picodata 2.10 or newer.\n",
     "gridPos": { "h": 8, "w": 8, "x": 8, "y": 13 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "tnt_memtx_tnx_user{instance=~\"$instance\",job=~\"$job\",kind=\"average\"}",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "Transaction user size (max)",
     "type": "timeseries",
     "description": "User may allocate memory for the current transaction with\nPicodata C APIfunction `box_txn_alloc()`.\n\nGraph shows the maximum number of bytes allocated over all current transactions.\n\nPanel works with metrics 0.15.1 or newer, Picodata 2.10 or newer.\n",
     "gridPos": { "h": 8, "w": 8, "x": 16, "y": 13 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "tnt_memtx_tnx_user{instance=~\"$instance\",job=~\"$job\",kind=\"max\"}",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "Transaction system size (total)",
     "type": "timeseries",
     "description": "System may store utility things like logs and savepoints\nfor each transaction.\n\nGraph shows memory allocated for all current transactions.\n\nPanel works with metrics 0.15.1 or newer, Picodata 2.10 or newer.\n",
     "gridPos": { "h": 8, "w": 8, "x": 0, "y": 29 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "tnt_memtx_tnx_system{instance=~\"$instance\",job=~\"$job\",kind=\"total\"}",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "Transaction system size (average)",
     "type": "timeseries",
     "description": "System may store utility things like logs and savepoints\nfor each transaction.\n\nGraph shows transaction average\n(total allocated bytes / number of all current transactions).\n\nPanel works with metrics 0.15.1 or newer, Picodata 2.10 or newer.\n",
     "gridPos": { "h": 8, "w": 8, "x": 8, "y": 29 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "tnt_memtx_tnx_system{instance=~\"$instance\",job=~\"$job\",kind=\"average\"}",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "Transaction system size (max)",
     "type": "timeseries",
     "description": "System may store utility things like logs and savepoints\nfor each transaction.\n\nGraph shows the maximum number of bytes allocated over all current transactions.\n\nPanel works with metrics 0.15.1 or newer, Picodata 2.10 or newer.\n",
     "gridPos": { "h": 8, "w": 8, "x": 16, "y": 29 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "tnt_memtx_tnx_system{instance=~\"$instance\",job=~\"$job\",kind=\"max\"}",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "Trackers size (total)",
     "type": "timeseries",
     "description": "Picodata allocates memory for trackers\nthat keep track of transaction reads.\n\nGraph shows memory allocated for trackers of all current transactions.\n\nPanel works with metrics 0.15.1 or newer, Picodata 2.10 or newer.\n",
     "gridPos": { "h": 8, "w": 8, "x": 0, "y": 37 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "tnt_memtx_mvcc_trackers{instance=~\"$instance\",job=~\"$job\",kind=\"total\"}",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "Trackers size (average)",
     "type": "timeseries",
     "description": "Picodata allocates memory for trackers\nthat keep track of transaction reads.\n\nGraph shows transaction tracker average\n(total allocated bytes / number of all current transactions).\n\nPanel works with metrics 0.15.1 or newer, Picodata 2.10 or newer.\n",
     "gridPos": { "h": 8, "w": 8, "x": 8, "y": 37 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "tnt_memtx_mvcc_trackers{instance=~\"$instance\",job=~\"$job\",kind=\"average\"}",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "Trackers size (max)",
     "type": "timeseries",
     "description": "Picodata allocates memory for trackers\nthat keep track of transaction reads.\n\nGraph shows the maximum number of bytes allocated for a tracker\nover all current transactions.\n\nPanel works with metrics 0.15.1 or newer, Picodata 2.10 or newer.\n",
     "gridPos": { "h": 8, "w": 8, "x": 16, "y": 37 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "tnt_memtx_mvcc_trackers{instance=~\"$instance\",job=~\"$job\",kind=\"max\"}",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "Conflicts size (total)",
     "type": "timeseries",
     "description": "Picodata allocates memory in case of conflicts.\n\nGraph shows memory allocated for all current conflicts.\n\nPanel works with metrics 0.15.1 or newer, Picodata 2.10 or newer.\n",
     "gridPos": { "h": 8, "w": 8, "x": 0, "y": 45 },
     "targets": [
      {
       "expr": "tnt_memtx_mvcc_conflicts{instance=~\"$instance\",job=~\"$job\",kind=\"total\"}",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "Conflicts size (average)",
     "type": "timeseries",
     "description": "Picodata allocates memory in case of conflicts.\n\nGraph shows transaction conflict average\n(total allocated bytes / number of all current conflict).\n\nPanel works with metrics 0.15.1 or newer, Picodata 2.10 or newer.\n",
     "gridPos": { "h": 8, "w": 8, "x": 8, "y": 45 },
     "targets": [
      {
       "expr": "tnt_memtx_mvcc_conflicts{instance=~\"$instance\",job=~\"$job\",kind=\"average\"}",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "Conflicts size (max)",
     "type": "timeseries",
     "description": "Picodata allocates memory in case of conflicts.\n\nGraph shows the maximum number of bytes allocated for a transaction conflict.\n\nPanel works with metrics 0.15.1 or newer, Picodata 2.10 or newer.\n",
     "gridPos": { "h": 8, "w": 8, "x": 16, "y": 45 },
     "targets": [
      {
       "expr": "tnt_memtx_mvcc_conflicts{instance=~\"$instance\",job=~\"$job\",kind=\"max\"}",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "Stories tuples used",
     "type": "timeseries",
     "description": "MVCC is based on the tuple story mechanism.\n\nThis graph shows tuples that are used by active read-write transactions.\n\nGraph shows the number of tuples.\nPanel works with metrics 0.15.1 or newer, Picodata 2.10 or newer.\n",
     "gridPos": { "h": 8, "w": 6, "x": 0, "y": 53 },
     "targets": [
      {
       "expr": "tnt_memtx_mvcc_tuples_used_stories{instance=~\"$instance\",job=~\"$job\",kind=\"count\"}",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "Stories tuples used size",
     "type": "timeseries",
     "description": "MVCC is based on the tuple story mechanism.\n\nThis graph shows tuples that are used by active read-write transactions.\n\nGraph shows total size of tuples.\nPanel works with metrics 0.15.1 or newer, Picodata 2.10 or newer.\n",
     "gridPos": { "h": 8, "w": 6, "x": 6, "y": 53 },
     "targets": [
      {
       "expr": "tnt_memtx_mvcc_tuples_used_stories{instance=~\"$instance\",job=~\"$job\",kind=\"total\"}",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "Retained tuples used",
     "type": "timeseries",
     "description": "Retained tuples are no longer in the index,\nbut MVCC does not allow them to be removed.\n\nThis graph shows tuples that are used by active read-write transactions.\n\nGraph shows the number of tuples.\nPanel works with metrics 0.15.1 or newer, Picodata 2.10 or newer.\n",
     "gridPos": { "h": 8, "w": 6, "x": 12, "y": 53 },
     "targets": [
      {
       "expr": "tnt_memtx_mvcc_tuples_used_retained{instance=~\"$instance\",job=~\"$job\",kind=\"count\"}",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "Retained tuples used size",
     "type": "timeseries",
     "description": "Retained tuples are no longer in the index,\nbut MVCC does not allow them to be removed.\n\nThis graph shows tuples that are used by active read-write transactions.\n\nGraph shows total size of tuples.\nPanel works with metrics 0.15.1 or newer, Picodata 2.10 or newer.\n",
     "gridPos": { "h": 8, "w": 6, "x": 18, "y": 53 },
     "targets": [
      {
       "expr": "tnt_memtx_mvcc_tuples_used_retained{instance=~\"$instance\",job=~\"$job\",kind=\"total\"}",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "Stories tuples in read views",
     "type": "timeseries",
     "description": "MVCC is based on the tuple story mechanism.\n\nThis graph shows tuples that are used by read-only transactions (i.e. in read view).\n\nGraph shows the number of tuples.\nPanel works with metrics 0.15.1 or newer, Picodata 2.10 or newer.\n",
     "gridPos": { "h": 8, "w": 6, "x": 0, "y": 61 },
     "targets": [
      {
       "expr": "tnt_memtx_mvcc_tuples_read_view_stories{instance=~\"$instance\",job=~\"$job\",kind=\"count\"}",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "Stories tuples in read views size",
     "type": "timeseries",
     "description": "MVCC is based on the tuple story mechanism.\n\nThis graph shows tuples that are used by read-only transactions (i.e. in read view).\n\nGraph shows total size of tuples.\nPanel works with metrics 0.15.1 or newer, Picodata 2.10 or newer.\n",
     "gridPos": { "h": 8, "w": 6, "x": 6, "y": 61 },
     "targets": [
      {
       "expr": "tnt_memtx_mvcc_tuples_read_view_stories{instance=~\"$instance\",job=~\"$job\",kind=\"total\"}",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "Retained tuples in read views",
     "type": "timeseries",
     "description": "Retained tuples are no longer in the index,\nbut MVCC does not allow them to be removed.\n\nThis graph shows tuples that are used by read-only transactions (i.e. in read view).\n\nGraph shows the number of tuples.\nPanel works with metrics 0.15.1 or newer, Picodata 2.10 or newer.\n",
     "gridPos": { "h": 8, "w": 6, "x": 12, "y": 61 },
     "targets": [
      {
       "expr": "tnt_memtx_mvcc_tuples_read_view_retained{instance=~\"$instance\",job=~\"$job\",kind=\"count\"}",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "Retained tuples in read views size",
     "type": "timeseries",
     "description": "Retained tuples are no longer in the index,\nbut MVCC does not allow them to be removed.\n\nThis graph shows tuples that are used by read-only transactions (i.e. in read view).\n\nGraph shows total size of tuples.\nPanel works with metrics 0.15.1 or newer, Picodata 2.10 or newer.\n",
     "gridPos": { "h": 8, "w": 6, "x": 18, "y": 61 },
     "targets": [
      {
       "expr": "tnt_memtx_mvcc_tuples_read_view_retained{instance=~\"$instance\",job=~\"$job\",kind=\"total\"}",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "Stories tuples tracked",
     "type": "timeseries",
     "description": "MVCC is based on the tuple story mechanism.\n\nThis graph shows tuples that are not used by current transactions,\nbut are used by MVCC to track reads.\n\nGraph shows the number of tuples.\nPanel works with metrics 0.15.1 or newer, Picodata 2.10 or newer.\n",
     "gridPos": { "h": 8, "w": 6, "x": 0, "y": 69 },
     "targets": [
      {
       "expr": "tnt_memtx_mvcc_tuples_tracking_stories{instance=~\"$instance\",job=~\"$job\",kind=\"count\"}",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "Stories tuples tracked size",
     "type": "timeseries",
     "description": "MVCC is based on the tuple story mechanism.\n\nThis graph shows tuples that are not used by current transactions,\nbut are used by MVCC to track reads.\n\nGraph shows total size of tuples.\nPanel works with metrics 0.15.1 or newer, Picodata 2.10 or newer.\n",
     "gridPos": { "h": 8, "w": 6, "x": 6, "y": 69 },
     "targets": [
      {
       "expr": "tnt_memtx_mvcc_tuples_tracking_stories{instance=~\"$instance\",job=~\"$job\",kind=\"total\"}",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "Retained tuples tracked",
     "type": "timeseries",
     "description": "Retained tuples are no longer in the index,\nbut MVCC does not allow them to be removed.\n\nThis graph shows tuples that are not used by current transactions,\nbut are used by MVCC to track reads.\n\nGraph shows the number of tuples.\nPanel works with metrics 0.15.1 or newer, Picodata 2.10 or newer.\n",
     "gridPos": { "h": 8, "w": 6, "x": 12, "y": 69 },
     "targets": [
      {
       "expr": "tnt_memtx_mvcc_tuples_tracking_retained{instance=~\"$instance\",job=~\"$job\",kind=\"count\"}",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "Retained tuples tracked size",
     "type": "timeseries",
     "description": "Retained tuples are no longer in the index,\nbut MVCC does not allow them to be removed.\n\nThis graph shows tuples that are not used by current transactions,\nbut are used by MVCC to track reads.\n\nGraph shows total size of tuples.\nPanel works with metrics 0.15.1 or newer, Picodata 2.10 or newer.\n",
     "gridPos": { "h": 8, "w": 6, "x": 18, "y": 69 },
     "targets": [
      {
       "expr": "tnt_memtx_mvcc_tuples_tracking_retained{instance=~\"$instance\",job=~\"$job\",kind=\"total\"}",
       "legendFormat": "{{instance}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Picodata table statistics",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 64 },
   "collapsed": true,
   "panels": [
    {
     "title": "Number of records (memtx)",
     "type": "timeseries",
     "description": "Number of records in the space (memtx engine).\nName of space is specified after dash.\n",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 6 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "tnt_space_len{instance=~\"$instance\",engine=\"memtx\",job=~\"$job\"}",
       "legendFormat": "{{instance}} — {{name}}"
      }
     ]
    },
    {
     "title": "Number of records (vinyl)",
     "type": "timeseries",
     "description": "Number of records in the space (vinyl engine).\nName of space is specified after dash.\nBy default this metrics is disabled,\nto enable it you must set global variable\ninclude_vinyl_count to true. Beware that\ncount() operation scans the space and may\nslow down your app. \n\nPanel works with `metrics >= 0.13.0`.\n",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 6 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "tnt_vinyl_tuples{instance=~\"$instance\",engine=\"vinyl\",job=~\"$job\"}",
       "legendFormat": "{{instance}} — {{name}}"
      }
     ]
    },
    {
     "title": "Data size (memtx)",
     "type": "timeseries",
     "description": "Total number of bytes in all tuples of the space (memtx engine).\nName of space is specified after dash.\n",
     "gridPos": { "h": 8, "w": 8, "x": 0, "y": 14 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "tnt_space_bsize{instance=~\"$instance\",engine=\"memtx\",job=~\"$job\"}",
       "legendFormat": "{{instance}} — {{name}}"
      }
     ]
    },
    {
     "title": "Index size",
     "type": "timeseries",
     "description": "Total number of bytes taken by the index.\nName of space is specified after dash,\nindex name specified in parentheses.\nIncludes both memtx and vinyl spaces.\n",
     "gridPos": { "h": 8, "w": 8, "x": 8, "y": 14 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "tnt_space_index_bsize{instance=~\"$instance\",job=~\"$job\"}",
       "legendFormat": "{{instance}} — {{name}} ({{index_name}})"
      }
     ]
    },
    {
     "title": "Total size (memtx)",
     "type": "timeseries",
     "description": "Total size of tuples and all indexes in the space (memtx engine).\nName of space is specified after dash.\n",
     "gridPos": { "h": 8, "w": 8, "x": 16, "y": 14 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "tnt_space_total_bsize{instance=~\"$instance\",engine=\"memtx\",job=~\"$job\"}",
       "legendFormat": "{{instance}} — {{name}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Picodata vinyl statistics",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 65 },
   "collapsed": true,
   "panels": [
    {
     "title": "Vinyl disk data",
     "type": "timeseries",
     "description": "The amount of data stored in the `.run` files located in the `vinyl_dir` directory.\n\nPanel works with `metrics >= 0.8.0`.\n",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 7 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "tnt_vinyl_disk_data_size{instance=~\"$instance\",job=~\"$job\"}",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "Vinyl disk index",
     "type": "timeseries",
     "description": "The amount of data stored in the `.index` files located in the `vinyl_dir` directory.\n\nPanel works with `metrics >= 0.8.0`.\n",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 7 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "tnt_vinyl_disk_index_size{instance=~\"$instance\",job=~\"$job\"}",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "Tuples cache memory",
     "type": "timeseries",
     "description": "Amount of memory in bytes currently used to store tuples (data).\n\nPanel works with `metrics >= 0.8.0`.\n",
     "gridPos": { "h": 8, "w": 8, "x": 0, "y": 15 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "tnt_vinyl_memory_tuple_cache{instance=~\"$instance\",job=~\"$job\"}",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "Index memory",
     "type": "timeseries",
     "description": "Amount of memory in bytes currently used to store indexes.\nIf the metric value is close to box.cfg.vinyl_memory, this\nindicates that vinyl_page_size was chosen incorrectly.\n\nPanel works with `metrics >= 0.8.0`.\n",
     "gridPos": { "h": 8, "w": 8, "x": 8, "y": 15 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "tnt_vinyl_memory_page_index{instance=~\"$instance\",job=~\"$job\"}",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "Bloom filter memory",
     "type": "timeseries",
     "description": "Amount of memory in bytes used by bloom filters.\n",
     "gridPos": { "h": 8, "w": 8, "x": 16, "y": 15 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "tnt_vinyl_memory_bloom_filter{instance=~\"$instance\",job=~\"$job\"}",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "Vinyl regulator dump bandwidth",
     "type": "timeseries",
     "description": "The estimated average rate of taking dumps, bytes per second.\nInitially, the rate value is 10 megabytes per second\nand being recalculated depending on the the actual rate.\nOnly significant dumps that are larger than one megabyte\nare used for the estimate.\n\nPanel works with `metrics >= 0.8.0`.\n",
     "gridPos": { "h": 8, "w": 8, "x": 0, "y": 31 },
     "fieldConfig": { "defaults": { "unit": "Bps" } },
     "targets": [
      {
       "expr": "tnt_vinyl_regulator_dump_bandwidth{instance=~\"$instance\",job=~\"$job\"}",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "Vinyl regulator write rate",
     "type": "timeseries",
     "description": "The actual average rate of performing the write operations, bytes per second.\nThe rate is calculated as a 5-second moving average.\nIf the metric value is gradually going down, this can indicate some disk issues.\n\nPanel works with `metrics >= 0.8.0`.\n",
     "gridPos": { "h": 8, "w": 8, "x": 8, "y": 31 },
     "fieldConfig": { "defaults": { "unit": "Bps" } },
     "targets": [
      {
       "expr": "tnt_vinyl_regulator_write_rate{instance=~\"$instance\",job=~\"$job\"}",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "Vinyl regulator rate limit",
     "type": "timeseries",
     "description": "The write rate limit, bytes per second.\nThe regulator imposes the limit on transactions based on the observed dump/compaction performance.\nIf the metric value is down to approximately 100 Kbps,\nthis indicates issues with the disk or the scheduler.\n\nPanel works with `metrics >= 0.8.0`.\n",
     "gridPos": { "h": 8, "w": 8, "x": 16, "y": 31 },
     "fieldConfig": { "defaults": { "unit": "Bps" } },
     "targets": [
      {
       "expr": "tnt_vinyl_regulator_rate_limit{instance=~\"$instance\",job=~\"$job\"}",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "Level 0 memory",
     "type": "timeseries",
     "description": "«Level 0» (L0) memory area in bytes. L0 is the area that\nvinyl can use for in-memory storage of an LSM tree.\nBy monitoring this metric, you can see when L0 is getting\nclose to its maximum (tnt_vinyl_regulator_dump_watermark),\nat which time a dump will occur. You can expect L0 = 0\nimmediately after the dump operation is completed.\n\nPanel works with `metrics >= 0.8.0`.\n",
     "gridPos": { "h": 8, "w": 8, "x": 0, "y": 39 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "tnt_vinyl_memory_level0{instance=~\"$instance\",job=~\"$job\"}",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "Vinyl regulator dump watermark",
     "type": "timeseries",
     "description": "The maximum amount of memory used for in-memory storing of a vinyl LSM tree.\nWhen accessing this maximum, the dumping must occur.\nFor details, see https://www.Picodata.io/en/doc/latest/book/box/engines/#engines-algorithm-filling-lsm.\nThe value is slightly smaller than the amount of memory allocated for vinyl trees,\nwhich is the `vinyl_memory` parameter.\n\nPanel works with `metrics >= 0.8.0`.\n",
     "gridPos": { "h": 8, "w": 8, "x": 8, "y": 39 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "tnt_vinyl_regulator_dump_watermark{instance=~\"$instance\",job=~\"$job\"}",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "Vinyl regulator blocked writers",
     "type": "timeseries",
     "description": "The number of fibers that are blocked waiting for Vinyl level0 memory quota.\n\nPanel works with `metrics >= 0.13.0` and `Picodata >= 2.8.3`.\n",
     "gridPos": { "h": 8, "w": 8, "x": 16, "y": 39 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "tnt_vinyl_regulator_blocked_writers{instance=~\"$instance\",job=~\"$job\"}",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "Vinyl tx commit rate",
     "type": "timeseries",
     "description": "Average per second rate of commits (successful transaction ends).\nIt includes implicit commits: for example, any insert operation causes a commit\nunless it is within a `box.begin()`–`box.commit()` block.\n\nPanel works with `metrics >= 0.8.0`.\n",
     "gridPos": { "h": 8, "w": 6, "x": 0, "y": 47 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "rate(tnt_vinyl_tx_commit{instance=~\"$instance\",job=~\"$job\"}[$__rate_interval])",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "Vinyl tx rollback rate",
     "type": "timeseries",
     "description": "Average per second rate of rollbacks (unsuccessful transaction ends).\nThis is not merely a count of explicit `box.rollback()` requests — it includes requests\nthat ended with errors.\nPanel works with `metrics >= 0.8.0`.\n",
     "gridPos": { "h": 8, "w": 6, "x": 6, "y": 47 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "rate(tnt_vinyl_tx_rollback{instance=~\"$instance\",job=~\"$job\"}[$__rate_interval])",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "Vinyl tx conflict rate",
     "type": "timeseries",
     "description": "Average per second rate of conflicts that caused transactions to roll back.\nThe ratio `tx conflicts` / `tx commits` above 5% indicates that vinyl is not healthy.\nAt this moment you’ll probably see a lot of other problems with vinyl.\n\nPanel works with `metrics >= 0.8.0`.\n",
     "gridPos": { "h": 8, "w": 6, "x": 12, "y": 47 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "rate(tnt_vinyl_tx_conflict{instance=~\"$instance\",job=~\"$job\"}[$__rate_interval])",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "Vinyl read views",
     "type": "timeseries",
     "description": "Number of current read views, that is, transactions entered a read-only state\nto avoid conflict temporarily.\nIf the value stays non-zero for a long time, it indicates of a memory leak.\n\nPanel works with `metrics >= 0.8.0`.\n",
     "gridPos": { "h": 8, "w": 6, "x": 18, "y": 47 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "tnt_vinyl_tx_read_views{instance=~\"$instance\",job=~\"$job\"}",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "Vinyl scheduler tasks in progress",
     "type": "timeseries",
     "description": "The number of the scheduler dump/compaction tasks in progress now.\n\nPanel works with `metrics >= 0.8.0`.\n",
     "gridPos": { "h": 8, "w": 6, "x": 0, "y": 55 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "tnt_vinyl_scheduler_tasks{instance=~\"$instance\",job=~\"$job\",status=\"inprogress\"}",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "Vinyl scheduler failed tasks rate",
     "type": "timeseries",
     "description": "Scheduler dump/compaction tasks failed.\nAverage per second rate is shown.\n\nPanel works with `metrics >= 0.8.0`.\n",
     "gridPos": { "h": 8, "w": 6, "x": 6, "y": 55 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "rate(tnt_vinyl_scheduler_tasks{instance=~\"$instance\",job=~\"$job\",status=\"failed\"}[$__rate_interval])",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "Vinyl scheduler dump time rate",
     "type": "timeseries",
     "description": "Time spent by all worker threads performing dumps.\nAverage per second rate is shown.\n\nPanel works with `metrics >= 0.8.0`.\n",
     "gridPos": { "h": 8, "w": 6, "x": 12, "y": 55 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "rate(tnt_vinyl_scheduler_dump_time{instance=~\"$instance\",job=~\"$job\"}[$__rate_interval])",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "Vinyl scheduler dump count rate",
     "type": "timeseries",
     "description": "Scheduler dumps completed average per second rate.\n\nPanel works with `metrics >= 0.13.0`.\n",
     "gridPos": { "h": 8, "w": 6, "x": 18, "y": 55 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "rate(tnt_vinyl_scheduler_dump_total{instance=~\"$instance\",job=~\"$job\"}[$__rate_interval])",
       "legendFormat": "{{instance}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Picodata CPU statistics",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 66 },
   "collapsed": true,
   "panels": [
    {
     "title": "CPU system/user time",
     "type": "timeseries",
     "description": "This is the average share of time\nspent by instance process executing in user mode.\nMetrics obtained using `getrusage()` call.\n",
     "gridPos": { "h": 9, "w": 24, "x": 0, "y": 84 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "targets": [
      {
       "expr": "irate(tnt_cpu_user_time{instance=~\"$instance\",job=~\"$job\"}[$__rate_interval]) + irate(tnt_cpu_system_time{instance=~\"$instance\",job=~\"$job\"}[$__rate_interval])",
       "legendFormat": "{{instance}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Picodata runtime overview",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 67 },
   "collapsed": true,
   "panels": [
    {
     "title": "Lua memory",
     "type": "timeseries",
     "description": "Memory used for objects allocated with Lua\nby using its internal mechanisms.\nLua memory is bounded by 2 GB per instance. \n",
     "gridPos": { "h": 8, "w": 8, "x": 0, "y": 9 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "tnt_info_memory_lua{instance=~\"$instance\",job=~\"$job\"}",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "Runtime arena memory",
     "type": "timeseries",
     "description": "Memory used by runtime arena.\nRuntime arena stores network buffers, tuples\ncreated with box.tuple.new and other objects\nallocated by application not covered by basic\nLua mechanisms (spaces data and indexes\nare not included here, see memtx/vinyl arena).\n",
     "gridPos": { "h": 8, "w": 8, "x": 8, "y": 9 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "tnt_runtime_used{instance=~\"$instance\",job=~\"$job\"}",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "Transactions memory",
     "type": "timeseries",
     "description": "Memory in use by active transactions.\nFor the vinyl storage engine, this is the total size of\nall allocated objects (struct txv, struct vy_tx, struct vy_read_interval)\nand tuples pinned for those objects. \n",
     "gridPos": { "h": 8, "w": 8, "x": 16, "y": 9 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "tnt_info_memory_tx{instance=~\"$instance\",job=~\"$job\"}",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "Fiber context switches",
     "type": "timeseries",
     "description": "Number of fiber context switches.\nContext switches are counted over all current fibers.\n",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 17 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "tnt_fiber_csw{instance=~\"$instance\",job=~\"$job\"}",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "Event loop time",
     "type": "timeseries",
     "description": "Duration of last event loop iteration (tx thread).\nHigh duration results in longer responses,\npossible bad health signals and may be the\nreason of \"Too long WAL write\" errors.\n\nPanel works with `metrics >= 0.13.0`.\n",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 17 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "targets": [
      {
       "expr": "tnt_ev_loop_time{instance=~\"$instance\",job=~\"$job\"}",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "Number of fibers",
     "type": "timeseries",
     "description": "Current number of fibers in tx thread. \n\nPanel works with `metrics >= 0.13.0`.\n",
     "gridPos": { "h": 8, "w": 8, "x": 0, "y": 33 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "tnt_fiber_amount{instance=~\"$instance\",job=~\"$job\"}",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "Memory used by fibers",
     "type": "timeseries",
     "description": "Amount of memory used by current fibers.\n",
     "gridPos": { "h": 8, "w": 8, "x": 8, "y": 33 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "tnt_fiber_memused{instance=~\"$instance\",job=~\"$job\"}",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "Memory reserved for fibers",
     "type": "timeseries",
     "description": "Amount of memory reserved for current fibers.\n",
     "gridPos": { "h": 8, "w": 8, "x": 16, "y": 33 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "tnt_fiber_memalloc{instance=~\"$instance\",job=~\"$job\"}",
       "legendFormat": "{{instance}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Picodata LuaJit statistics",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 68 },
   "collapsed": true,
   "panels": [
    {
     "title": "Snap restores",
     "type": "timeseries",
     "description": "Average number of snap restores (guard assertions\nleading to stopping trace executions) per second.\n\n\nPanel works with `metrics >= 0.15.0` and `Picodata >= 2.6`.",
     "gridPos": { "h": 8, "w": 6, "x": 0, "y": 10 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "rate(lj_jit_snap_restore_total{instance=~\"$instance\",job=~\"$job\"}[$__rate_interval])",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "JIT traces written",
     "type": "timeseries",
     "description": "Average number of new JIT traces per second.\n\n\nPanel works with `metrics >= 0.6.0` and `Picodata >= 2.6`.",
     "gridPos": { "h": 8, "w": 6, "x": 6, "y": 10 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "rate(lj_jit_trace_num{instance=~\"$instance\",job=~\"$job\"}[$__rate_interval])",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "JIT traces aborted",
     "type": "timeseries",
     "description": "Average number of JIT trace aborts per second.\n\n\nPanel works with `metrics >= 0.15.0` and `Picodata >= 2.6`.",
     "gridPos": { "h": 8, "w": 6, "x": 12, "y": 10 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "rate(lj_jit_trace_abort_total{instance=~\"$instance\",job=~\"$job\"}[$__rate_interval])",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "Machine code areas",
     "type": "timeseries",
     "description": "Total size of allocated machine code areas.\n\n\nPanel works with `metrics >= 0.6.0` and `Picodata >= 2.6`.",
     "gridPos": { "h": 8, "w": 6, "x": 18, "y": 10 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "lj_jit_mcode_size{instance=~\"$instance\",job=~\"$job\"}",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "Strings interned",
     "type": "timeseries",
     "description": "Average number of strings being extracted from hash instead of allocating per second.\n\n\nPanel works with `metrics >= 0.15.0` and `Picodata >= 2.6`.",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 26 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "rate(lj_strhash_hit_total{instance=~\"$instance\",job=~\"$job\"}[$__rate_interval])",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "Strings allocated",
     "type": "timeseries",
     "description": "Average number of strings being allocated due to hash miss per second.\n\n\nPanel works with `metrics >= 0.15.0` and `Picodata >= 2.6`.",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 26 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "rate(lj_strhash_miss_total{instance=~\"$instance\",job=~\"$job\"}[$__rate_interval])",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "GC steps (atomic)",
     "type": "timeseries",
     "description": "Average count of incremental GC steps (atomic state) per second.\n\n\nPanel works with `metrics >= 0.15.0` and `Picodata >= 2.6`.",
     "gridPos": { "h": 8, "w": 8, "x": 0, "y": 34 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "rate(lj_gc_steps_atomic_total{instance=~\"$instance\",job=~\"$job\"}[$__rate_interval])",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "GC steps (sweepstring)",
     "type": "timeseries",
     "description": "Average count of incremental GC steps (sweepstring state) per second.\n\n\nPanel works with `metrics >= 0.15.0` and `Picodata >= 2.6`.",
     "gridPos": { "h": 8, "w": 8, "x": 8, "y": 34 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "rate(lj_gc_steps_sweepstring_total{instance=~\"$instance\",job=~\"$job\"}[$__rate_interval])",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "GC steps (finalize)",
     "type": "timeseries",
     "description": "Average count of incremental GC steps (finalize state) per second.\n\n\nPanel works with `metrics >= 0.15.0` and `Picodata >= 2.6`.",
     "gridPos": { "h": 8, "w": 8, "x": 16, "y": 34 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "rate(lj_gc_steps_finalize_total{instance=~\"$instance\",job=~\"$job\"}[$__rate_interval])",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "GC steps (sweep)",
     "type": "timeseries",
     "description": "Average count of incremental GC steps (sweep state) per second.\n\n\nPanel works with `metrics >= 0.15.0` and `Picodata >= 2.6`.",
     "gridPos": { "h": 8, "w": 8, "x": 0, "y": 42 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "rate(lj_gc_steps_sweep_total{instance=~\"$instance\",job=~\"$job\"}[$__rate_interval])",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "GC steps (propagate)",
     "type": "timeseries",
     "description": "Average count of incremental GC steps (propagate state) per second.\n\n\nPanel works with `metrics >= 0.15.0` and `Picodata >= 2.6`.",
     "gridPos": { "h": 8, "w": 8, "x": 8, "y": 42 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "rate(lj_gc_steps_propagate_total{instance=~\"$instance\",job=~\"$job\"}[$__rate_interval])",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "GC steps (pause)",
     "type": "timeseries",
     "description": "Average count of incremental GC steps (pause state) per second.\n\n\nPanel works with `metrics >= 0.15.0` and `Picodata >= 2.6`.",
     "gridPos": { "h": 8, "w": 8, "x": 16, "y": 42 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "rate(lj_gc_steps_pause_total{instance=~\"$instance\",job=~\"$job\"}[$__rate_interval])",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "String objects allocated",
     "type": "timeseries",
     "description": "Number of allocated string objects.\n\n\nPanel works with `metrics >= 0.6.0` and `Picodata >= 2.6`.",
     "gridPos": { "h": 8, "w": 6, "x": 0, "y": 50 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "lj_gc_strnum{instance=~\"$instance\",job=~\"$job\"}",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "Table objects allocated",
     "type": "timeseries",
     "description": "Number of allocated table objects.\n\n\nPanel works with `metrics >= 0.6.0` and `Picodata >= 2.6`.",
     "gridPos": { "h": 8, "w": 6, "x": 6, "y": 50 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "lj_gc_tabnum{instance=~\"$instance\",job=~\"$job\"}",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "cdata objects allocated",
     "type": "timeseries",
     "description": "Number of allocated cdata objects.\n\n\nPanel works with `metrics >= 0.6.0` and `Picodata >= 2.6`.",
     "gridPos": { "h": 8, "w": 6, "x": 12, "y": 50 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "lj_gc_cdatanum{instance=~\"$instance\",job=~\"$job\"}",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "userdata objects allocated",
     "type": "timeseries",
     "description": "Number of allocated userdata objects.\n\n\nPanel works with `metrics >= 0.6.0` and `Picodata >= 2.6`.",
     "gridPos": { "h": 8, "w": 6, "x": 18, "y": 50 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "lj_gc_udatanum{instance=~\"$instance\",job=~\"$job\"}",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "Current Lua memory",
     "type": "timeseries",
     "description": "Current allocated Lua memory.\n\n\nPanel works with `metrics >= 0.6.0` and `Picodata >= 2.6`.",
     "gridPos": { "h": 8, "w": 8, "x": 0, "y": 58 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "lj_gc_memory{instance=~\"$instance\",job=~\"$job\"}",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "Freed Lua memory",
     "type": "timeseries",
     "description": "Average amount of freed Lua memory per second.\n\n\nPanel works with `metrics >= 0.15.0` and `Picodata >= 2.6`.",
     "gridPos": { "h": 8, "w": 8, "x": 8, "y": 58 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "rate(lj_gc_freed_total{instance=~\"$instance\",job=~\"$job\"}[$__rate_interval])",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "Allocated Lua memory",
     "type": "timeseries",
     "description": "Average amount of allocated Lua memory per second.\n\n\nPanel works with `metrics >= 0.15.0` and `Picodata >= 2.6`.",
     "gridPos": { "h": 8, "w": 8, "x": 16, "y": 58 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "rate(lj_gc_allocated_total{instance=~\"$instance\",job=~\"$job\"}[$__rate_interval])",
       "legendFormat": "{{instance}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Picodata operations statistics",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 69 },
   "collapsed": true,
   "panels": [
    {
     "title": "SELECT space requests",
     "type": "timeseries",
     "description": "Total count of SELECT requests to all instance spaces.\nGraph shows average requests per second.\n",
     "gridPos": { "h": 8, "w": 8, "x": 0, "y": 11 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "rate(tnt_stats_op_total{instance=~\"$instance\",job=~\"$job\",operation=\"select\"}[$__rate_interval])",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "INSERT space requests",
     "type": "timeseries",
     "description": "Total count of INSERT requests to all instance spaces.\nGraph shows average requests per second.\n",
     "gridPos": { "h": 8, "w": 8, "x": 8, "y": 11 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "rate(tnt_stats_op_total{instance=~\"$instance\",job=~\"$job\",operation=\"insert\"}[$__rate_interval])",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "REPLACE space requests",
     "type": "timeseries",
     "description": "Total count of REPLACE requests to all instance spaces.\nGraph shows average requests per second.\n",
     "gridPos": { "h": 8, "w": 8, "x": 16, "y": 11 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "rate(tnt_stats_op_total{instance=~\"$instance\",job=~\"$job\",operation=\"replace\"}[$__rate_interval])",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "UPSERT space requests",
     "type": "timeseries",
     "description": "Total count of UPSERT requests to all instance spaces.\nGraph shows average requests per second.\n",
     "gridPos": { "h": 8, "w": 8, "x": 0, "y": 27 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "rate(tnt_stats_op_total{instance=~\"$instance\",job=~\"$job\",operation=\"upsert\"}[$__rate_interval])",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "UPDATE space requests",
     "type": "timeseries",
     "description": "Total count of UPDATE requests to all instance spaces.\nGraph shows average requests per second.\n",
     "gridPos": { "h": 8, "w": 8, "x": 8, "y": 27 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "rate(tnt_stats_op_total{instance=~\"$instance\",job=~\"$job\",operation=\"update\"}[$__rate_interval])",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "DELETE space requests",
     "type": "timeseries",
     "description": "Total count of DELETE requests to all instance spaces.\nGraph shows average requests per second.\n",
     "gridPos": { "h": 8, "w": 8, "x": 16, "y": 27 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "rate(tnt_stats_op_total{instance=~\"$instance\",job=~\"$job\",operation=\"delete\"}[$__rate_interval])",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "Call requests",
     "type": "timeseries",
     "description": "Requests to execute stored procedures.\nGraph shows average requests per second.\n",
     "gridPos": { "h": 8, "w": 8, "x": 0, "y": 35 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "rate(tnt_stats_op_total{instance=~\"$instance\",job=~\"$job\",operation=\"call\"}[$__rate_interval])",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "Eval calls",
     "type": "timeseries",
     "description": "Calls to evaluate Lua code.\nGraph shows average requests per second.\n",
     "gridPos": { "h": 8, "w": 8, "x": 8, "y": 35 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "rate(tnt_stats_op_total{instance=~\"$instance\",job=~\"$job\",operation=\"eval\"}[$__rate_interval])",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "Request errors",
     "type": "timeseries",
     "description": "Requests resulted in error.\nGraph shows average errors per second.\n",
     "gridPos": { "h": 8, "w": 8, "x": 16, "y": 35 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "rate(tnt_stats_op_total{instance=~\"$instance\",job=~\"$job\",operation=\"error\"}[$__rate_interval])",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "Authentication requests",
     "type": "timeseries",
     "description": "Authentication requests.\nGraph shows average requests per second.\n",
     "gridPos": { "h": 8, "w": 8, "x": 0, "y": 43 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "rate(tnt_stats_op_total{instance=~\"$instance\",job=~\"$job\",operation=\"auth\"}[$__rate_interval])",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "SQL prepare calls",
     "type": "timeseries",
     "description": "SQL prepare calls.\nGraph shows average calls per second.\n\nPanel works with Picodata 2.x.\n",
     "gridPos": { "h": 8, "w": 8, "x": 8, "y": 43 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "rate(tnt_stats_op_total{instance=~\"$instance\",job=~\"$job\",operation=\"prepare\"}[$__rate_interval])",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "SQL execute calls",
     "type": "timeseries",
     "description": "SQL execute calls.\nGraph shows average calls per second.\n\nPanel works with Picodata 2.x.\n",
     "gridPos": { "h": 8, "w": 8, "x": 16, "y": 43 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "rate(tnt_stats_op_total{instance=~\"$instance\",job=~\"$job\",operation=\"execute\"}[$__rate_interval])",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "Transaction begins",
     "type": "timeseries",
     "description": "Panel displays the count of IPROTO_CALL and\nIPROTO_EVAL operations with `box.begin()`, IPROTO_EXECUTE\noperations with `TRANSACTION START` and IPROTO_BEGIN operations.\nGraph shows average calls per second.\n\nPanel works with Picodata 2.10 or newer.\n",
     "gridPos": { "h": 8, "w": 8, "x": 0, "y": 51 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "rate(tnt_stats_op_total{instance=~\"$instance\",job=~\"$job\",operation=\"begin\"}[$__rate_interval])",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "Transaction commits",
     "type": "timeseries",
     "description": "Panel displays the count of IPROTO_CALL and\nIPROTO_EVAL operations with `box.commit()`, IPROTO_EXECUTE\noperations with `COMMIT` and IPROTO_COMMIT operations.\nGraph shows average calls per second.\n\nPanel works with Picodata 2.10 or newer.\n",
     "gridPos": { "h": 8, "w": 8, "x": 8, "y": 51 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "rate(tnt_stats_op_total{instance=~\"$instance\",job=~\"$job\",operation=\"commit\"}[$__rate_interval])",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "Transaction rollbacks",
     "type": "timeseries",
     "description": "Panel displays the count of IPROTO_CALL and\nIPROTO_EVAL operations with `box.rollback()`, IPROTO_EXECUTE\noperations with `ROLLBACK` and IPROTO_ROLLBACK operations.\nGraph shows average calls per second.\n\nPanel works with Picodata 2.10 or newer.\n",
     "gridPos": { "h": 8, "w": 8, "x": 16, "y": 51 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "rate(tnt_stats_op_total{instance=~\"$instance\",job=~\"$job\",operation=\"rollback\"}[$__rate_interval])",
       "legendFormat": "{{instance}}"
      }
     ]
    }
   ]
  }
 ]
}