[package]
name = "pico_proc_macro"
version = "0.1.0"
edition.workspace = true
license-file.workspace = true

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
proc-macro = true

[dependencies]
proc-macro2 = "1.0"
quote = { workspace = true }
syn = { version = "1.0", features = ["full", "extra-traits"] }
