services:
  picodata-1-1:
    image: ${REGISTRY:-docker-public.binary.picodata.io}/picodata:latest
    container_name: picodata-1-1
    hostname: picodata-1-1
    environment:
      PICODATA_ADMIN_PASSWORD: T0psecret
    volumes:
      - $PWD:/data
      - $PWD/picodata-1-1.conf:/var/lib/picodata/picodata.yaml
    ports:
      - "13301:3301"
      - "18301:8001"
      - "55432:5432"
    build:
      context: ../
      dockerfile: docker/picodata.Dockerfile
      args:
        - RUST_VERSION=stable

  picodata-1-2:
    image: ${REGISTRY:-docker-public.binary.picodata.io}/picodata:latest
    container_name: picodata-1-2
    hostname: picodata-1-2
    volumes:
      - $PWD:/data
      - $PWD/picodata-1-2.conf:/var/lib/picodata/picodata.yaml
    ports:
      - "13302:3301"
      - "18302:8001"

  picodata-2-1:
    image: ${REGISTRY:-docker-public.binary.picodata.io}/picodata:latest
    container_name: picodata-2-1
    hostname: picodata-2-1
    volumes:
      - $PWD:/data
      - $PWD/picodata-2-1.conf:/var/lib/picodata/picodata.yaml
    ports:
      - "13303:3301"
      - "18303:8001"

  picodata-2-2:
    image: ${REGISTRY:-docker-public.binary.picodata.io}/picodata:latest
    container_name: picodata-2-2
    hostname: picodata-2-2
    volumes:
      - $PWD:/data
      - $PWD/picodata-2-2.conf:/var/lib/picodata/picodata.yaml
    ports:
      - "13304:3301"
      - "18304:8001"
