cluster:
  name: my_cluster

  tier:
    default:
      replication_factor: 2

instance:
  instance_dir: '/data/picodata-2-2'
  name: 'picodata-2-2'
  tier: 'default'
  peer: [ picodata-1-1:3301 ]

  iproto:
    listen: '0.0.0.0:3301'
    advertise: 'picodata-2-2:3301'
  http:
    listen: '0.0.0.0:8001'
  pgproto:
    listen: '0.0.0.0:5432'
    advertise: 'picodata-2-2:5432'

  memtx:
    memory: 128M

  log:
    level: info
