[package]
name = "sql-ast-new-corpus"
version = "0.1.0"
rust-version.workspace = true
authors = ["Picodata"]
license-file.workspace = true
edition.workspace = true

[dependencies]
sql-executor = { path = "../sql-executor" }
sql-ir = { path = "../sql-ir" }
smol_str = { workspace = true }

[dev-dependencies]
sql-ast-new-parser = { path = "../sql-ast-new-parser" }
sql-ast-new-corpus = { path = "../sql-ast-new-corpus", features = ["mock"] }

[features]
mock = ["sql-executor/mock", "sql-ir/mock"]
