[package]
name = "sql-type-system"
version = "0.1.0"
edition = "2021"
license-file = "../LICENSE"

[dependencies]
criterion = "0.5.1"
thiserror = "2.0.12"

[[bench]]
name = "benchmark"
harness = false
