[package]
name = "sql-type-system"
version = "0.1.0"
edition.workspace = true
license-file.workspace = true

[dependencies]
criterion = "0.5.1"
thiserror = { workspace = true }

[[bench]]
name = "benchmark"
harness = false
