-- TEST: window9
-- SQL:
DROP TABLE IF EXISTS t4;
CREATE TABLE t4(a INTEGER PRIMARY KEY, b TEXT, c INTEGER);
INSERT INTO t4 VALUES(1, 'A', 9);
INSERT INTO t4 VALUES(2, 'B', 3);
INSERT INTO t4 VALUES(3, 'C', 2);
INSERT INTO t4 VALUES(4, 'D', 10);
INSERT INTO t4 VALUES(5, 'E', 5);
INSERT INTO t4 VALUES(6, 'F', 1);
INSERT INTO t4 VALUES(7, 'G', 1);
INSERT INTO t4 VALUES(8, 'H', 2);
INSERT INTO t4 VALUES(9, 'I', 10);
INSERT INTO t4 VALUES(10, 'J', 4);

-- TEST: window9-2.4.1
-- SQL:
SELECT group_concat(b, '.') OVER (
ORDER BY a ROWS BETWEEN CURRENT ROW AND UNBOUNDED FOLLOWING
) FROM t4
-- EXPECTED:
A.B.C.D.E.F.G.H.I.J,
B.C.D.E.F.G.H.I.J,
C.D.E.F.G.H.I.J,
D.E.F.G.H.I.J,
E.F.G.H.I.J,
F.G.H.I.J,
G.H.I.J,
H.I.J,
I.J,
J
