stages:
    - build
    - test

cache:
    key: ${CI_COMMIT_REF_SLUG}
    paths:
        - target

build:
    stage: build
    tags:
        - docker
    image: registry.gitlab.com/picodata/dockers/brod-builder:0.1
    script:
        - make

test:
    stage: test
    tags:
        - docker
    image: registry.gitlab.com/picodata/dockers/brod-builder:0.1
    script:
        - make test
