stages:
    - build
    - test

cache:
    key:
        files:
            - Cargo.toml
            - Cargo.lock
    paths:
        - target

build:
    stage: build
    tags:
        - docker
    image: registry.gitlab.com/picodata/dockers/brod-builder:0.2
    script:
        - cargo -V
        - make

test:
    stage: test
    tags:
        - docker
    image: registry.gitlab.com/picodata/dockers/brod-builder:0.2
    script:
        - make test
        - cargo test

pages:
  image: registry.gitlab.com/picodata/dockers/brod-builder:0.2
  stage: build
  only:
    - master
  script:
    - cargo doc
    - rm -rf public
    - mkdir public
    - cp -R target/doc/* public
  artifacts:
    paths:
    - public

