stages:
    - build
    - test

cache:
    key:
        files:
            - Cargo.toml
            - Cargo.lock
    paths:
        - target

build:
    stage: build
    tags:
        - docker
    image: registry.gitlab.com/picodata/dockers/brod-builder:0.2
    script:
        - make

test:
    stage: test
    tags:
        - docker
    image: registry.gitlab.com/picodata/dockers/brod-builder:0.2
    script:
        - make test
        - cargo test
