stages:
    - build
    - test
    - lint

variables:
    DOCKER_IMAGE: registry.gitlab.com/picodata/dockers/brod-builder:0.5

cache:
    key:
        files:
            - Cargo.toml
            - Cargo.lock
    paths:
        - target

build:
    stage: build
    tags:
        - docker
    image: ${DOCKER_IMAGE}
    script:
        - cargo -V
        - make

test:
    stage: test
    tags:
        - docker
    image: ${DOCKER_IMAGE}
    script:
        - make test
        - cargo test

lint:
    stage: lint
    tags:
        - docker
    image: ${DOCKER_IMAGE}
    script:
        - cargo clippy --version
        - cargo clippy -- --deny warnings

pages:
  image: ${DOCKER_IMAGE}
  stage: build
  only:
    - master
  script:
    - cargo doc
    - rm -rf public
    - mkdir public
    - cp -R target/doc/* public
  artifacts:
    paths:
    - public
