[package]
name = "tarantool-module"
version = "0.1.0"
authors = [
    "Dmitriy Koltsov <dkoltsov@picodata.io>",
    "Anton Melnikov <volt0@picodata.io>"
]
edition = "2018"
license = "MIT"
readme = "README.md"

[dependencies]
va_list = "0.1.3"
rmp = "0.8"
rmp-serde = "0.14"
serde = "1.0"
