[package]
name = "tarantool"
description = "Tarantool rust bindings"
version = "0.3.0"
authors = [
    "Dmitriy Koltsov <dkoltsov@picodata.io>",
    "Anton Melnikov <volt0@picodata.io>"
]
edition = "2018"
license = "BSD-2-Clause"
readme = "README.md"
documentation = "https://docs.rs/tarantool/"
repository = "https://github.com/picodata/tarantool-module"
keywords = ["ffi", "database", "tarantool"]
categories = ["database"]

[dependencies]
base64 = "0.13"
bitflags = "1.2"
byteorder = "1.3"
derivative = "2.1"
failure = "0.1.8"
libc = "0.2"
log = "0.4"
num-traits = "0.2"
num-derive = "0.3"
rmp = "0.8"
rmp-serde = "0.14"
serde = { version = "1.0", features = ["derive"] }
sha-1 = "0.9"
va_list = "0.1.3"

[workspace]
members = [
    "tests",
    "examples/easy",
    "examples/harder",
    "examples/hardest",
    "examples/read",
    "examples/write",
]
