[workspace]
exclude = [ "hlua" ]
members = [
    "tarantool",
    "tests",
    "examples/easy",
    "examples/harder",
    "examples/hardest",
    "examples/read",
    "examples/write",
    "examples/cluster_node"
]

