[package]
name = "tarantool-module"
version = "0.1.0"
authors = [
    "Dmitriy Koltsov <dkoltsov@picodata.io>",
    "Anton Melnikov <volt0@picodata.io>"
]
edition = "2018"
license = "BSD-2-Clause"
readme = "README.md"

[dependencies]
failure = "0.1.8"
num-traits = "0.2"
num-derive = "0.3"
rmp = "0.8"
rmp-serde = "0.14"
serde = "1.0"
va_list = "0.1.3"
