default:
  image:
    name: ${BASE_IMAGE_DOCS}:${BASE_IMAGE_TAG}
    pull_policy: always
  tags:
    - docker-k8s

variables:
  BASE_IMAGE_DOCS: ${CI_REGISTRY_IMAGE}/docs
  KANIKO_REGISTRY_MIRROR: docker-proxy.binary.picodata.io

workflow:
  rules:
    - if: $CI_PIPELINE_SOURCE == "parent_pipeline"

stages:
  - build-base-image
  - lint
  - pack
  - upload
  - deploy

build-docs-image:
  stage: build-base-image
  image:
    name: docker-public.binary.picodata.io/kaniko-project/executor:v1.23.1-debug
    entrypoint: [""]
    pull_policy: [if-not-present]
  variables:
    GIT_USERNAME: $CI_REGISTRY_USER
    GIT_PASSWORD: $CI_REGISTRY_PASSWORD
    DOCKERFILE: docker-build-base/docs.Dockerfile
    DESTINATION: ${BASE_IMAGE_DOCS}:${BASE_IMAGE_TAG}
  rules:
    - changes:
        paths:
          - docker-build-base/docs.Dockerfile
          - docs/.gitlab-ci.yml
        # we can use variable for compare_to option in downstream pipeline
        compare_to: $MAIN_BRANCH
    - changes:
        paths:
          - docker-build-base/docs.Dockerfile
          - docs/.gitlab-ci.yml
    - when: manual
      allow_failure: true
      variables:
        BASE_IMAGE_TAG: ${BASE_IMAGE_LATEST}
  script:
    - >
      /kaniko/executor --context $CI_PROJECT_DIR --dockerfile ${DOCKERFILE}
      --cache=false --cache-run-layers=true --single-snapshot --compressed-caching=false --use-new-run --snapshot-mode=redo --cleanup
      --destination ${DESTINATION}

lint-docs:
  stage: lint
  script:
    - echo "Checking picodata doc..."
    - pushd docs && pipenv run lint
    - echo "Picodata doc successfully checked"

pack-doc:
  stage: pack
  variables:
    SED_SLUG: "s/[^a-zA-Z0-9.]+/_/g"
  before_script:
    - |
      if [ "$CI_COMMIT_BRANCH" == "master" ]; then
        PICODATA_DOC_VER="devel"
      elif [ "$CI_COMMIT_BRANCH" == "$MAIN_BRANCH" ]; then
        PICODATA_DOC_VER="$MAIN_BRANCH"
      else
        PICODATA_DOC_VER="$(echo $CI_COMMIT_REF_NAME | sed -E "$SED_SLUG")"
      fi
    - |
      if [ "$CI_COMMIT_BRANCH" == "$MAIN_BRANCH" ]; then
        SITE_URL="https://docs.picodata.io/picodata/$PICODATA_DOC_VER"
      else
        SITE_URL="https://docs.binary.picodata.io/picodata/$PICODATA_DOC_VER"
      fi
    - cd docs/
  script:
    # Automatic Loading of .env — https://pipenv.pypa.io/en/stable/shell.html
    - echo "Pack picodata doc..."
    - echo "PICODATA_DOC_VER=$PICODATA_DOC_VER" | tee .env
    - echo "SITE_URL=$SITE_URL" | tee -a .env
    - DATE=$(date +%Y%m%d%H%M%S)
    - FNAME="picodata-doc-${DATE}-${PICODATA_DOC_VER}-${CI_COMMIT_SHA}.tgz"
    - echo "FNAME=$FNAME" | tee -a .env
    - echo "GIT_DESCRIBE=$(git describe --always)" | tee -a .env
    - pipenv run mkdocs build -sd build
    - pushd build
    - >
      chromium --headless --disable-gpu --no-sandbox --no-zygote
      --disable-software-rasterizer --disable-dev-shm-usage --no-pdf-header-footer
      --print-to-pdf=picodata_docs.pdf picodata_docs.html
    - cp picodata_docs.pdf ../
    - tar -cvzf ../$FNAME .
    - popd
    - echo "Picodata doc successfully packed."
  artifacts:
    name: "artifacts-vars-${CI_PIPELINE_ID}"
    paths:
      - docs/picodata-doc-*.tgz
      - docs/picodata_docs.pdf
    reports:
      dotenv: docs/.env

upload-doc-to-binary:
  image: docker.binary.picodata.io/curlimages/curl
  stage: upload
  variables:
    GIT_STRATEGY: none
  script:
    - cd docs/
    - echo "Upload picodata doc to binary..."
    - echo "FNAME=$FNAME"
    - 'curl --fail -H "Authorization: Basic ${WWW_RAW_RW}" --upload-file $FNAME https://binary.picodata.io/repository/www-raw/$FNAME'
    - echo "Picodata doc successfully uploaded to binary."

.deploy-doc:
  stage: deploy
  variables:
    PICODATA_DOC: $FNAME
    PICODATA_DOC_SUBDIR: $PICODATA_DOC_VER
  trigger:
    project: "picodata/web-site/infra"
    strategy: depend

deploy-doc-staging:
  extends:
    - .deploy-doc
  rules:
    - if: $PARENT_CI_PIPELINE_SOURCE == "merge_request_event"
  variables:
    STAGE: TEST

deploy-doc-prod:
  extends:
    - .deploy-doc
  rules:
    - if: ($CI_COMMIT_BRANCH == $MAIN_BRANCH) && ($PARENT_CI_PIPELINE_SOURCE != "schedule")
  variables:
    STAGE: PROD
